---
title: "Hawaii's Battle With COVID-19"
author: "David J Jackson"
date: "8/15/2020"
output: 
  html_document: 
    fig_width: 9
    fig_height: 7
---

```{r setup, include=FALSE,message=FALSE,echo=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen=5)
library(RSQLite)
```
```{r}
rm(list=ls())
source("../DATA/movavg.R")
db <- db <- dbConnect(RSQLite::SQLite(),dbname= "../COVIDDB/COVID.sqlite3")
df <- dbGetQuery(db,"select * from STATESDAILY")
df <- subset(df,state =="Hawaii" & new_cases >0 )
df$date <- as.Date(df$date)
str(df)

```
```{r}
US <- subset(df,date >="2020-04-01")
US$MA14 <- movingAverage(US$new_cases,14)
plot(US$date,US$new_cases,type="l",main="COVID-19 Cases Apr. 1,2020 - Aug. 12, 2020 \n ( Red line = 14 day moving avearge)",xlab="Date",ylab="Cases",col="blue") 
lines(US$date,US$MA14,col="red")
legend("bottomright",
       c("Daily Cases","14 Day Mov. Avg."),
       col=c("blue","red"),
       lty = c(1, 1),
       cex = 0.8,
       lwd=4)
grid(col="black")
```
```{r}
US <- subset(df,date >="2020-04-01" & date <="2020-08-015")
US$new_deaths14 <- movingAverage(US$new_deaths,14)
plot(US$date,US$new_deaths,type="l",main="COVID-19 Deaths Apr. 1,2020 - Aug. 12, 2020 \n (Red = 14 day moving average)",xlab="Date",ylab="Deaths",col="blue")
lines(US$date,US$new_deaths14,col="red")
legend("bottomright",
       c("Daily Deaths","14 Day Mov. Avg."),
       col=c("blue","red"),
       lty = c(1, 1),
       cex = 0.8,
       lwd=4)
grid(col="black")
```

#### Non-Moving Average By Week and By Month

```{r}
US$Monthly <- as.Date(cut(US$date,
  breaks = "month"))
US$Weekly <- as.Date(cut(US$date,
  breaks = "week",
  start.on.monday = FALSE))

```
```{r}
Weekly_new_cases <- aggregate(new_cases~Weekly,US,FUN=sum)
Weekly_new_deaths <- aggregate(new_deaths~Weekly,US,FUN=sum)

```
```{r}
barplot(new_cases ~Weekly,data=Weekly_new_cases,main="Weekly Barplot of Cases",xlab="Date",ylab="Cases")
grid(col="black")
barplot(new_deaths ~Weekly,data=Weekly_new_deaths,main="Weekly Barplot of Deaths",xlab="Date",ylab="Deaths")
grid(col="black")
```
```{r}

Monthly_new_cases <- aggregate(new_cases~Monthly,US,FUN=sum)
Monthly_new_deaths <- aggregate(new_deaths~Monthly,US,FUN=sum)
```
```{r}
barplot(new_cases ~Monthly,data=Monthly_new_cases,main="Monthly Barplot of Total Cases",xlab="Date",ylab="Cases" )
grid(col="black")
barplot(new_deaths ~Monthly,data=Monthly_new_deaths,main="Monthly Barplot of Total Deaths",xlab="Date",ylab="Deaths")
grid(col="black")
```

### Weekly and Monthly Mean COVID-19 new_cases And new_deaths

```{r}
Weekly_new_cases <- aggregate(new_cases~Weekly,US,FUN=mean)
Weekly_new_deaths <- aggregate(new_deaths~Weekly,US,FUN=mean)


barplot(new_cases ~Weekly,data=Weekly_new_cases,main="Weekly Barplot of Mean Cases",xlab="Date",ylab="Cases")
grid(col="black")
barplot(new_deaths ~Weekly,data=Weekly_new_deaths,main="Weekly Barplot of Mean Deaths",xlab="Date",ylab="Deaths")
grid(col="black")
```
```{r}
Monthly_new_cases <- aggregate(new_cases~Monthly,US,FUN=mean)
Monthly_new_deaths <- aggregate(new_deaths~Monthly,US,FUN=mean)


barplot(new_cases ~Monthly,data=Monthly_new_cases,main="Monthly Mean Barplot of Cases",xlab="Date",ylab="Cases")
grid(col="black")

barplot(new_deaths ~Monthly,data=Monthly_new_deaths,main="Monthly Mean Barplot of new_deaths",xlab="Date",ylab="Deaths")
grid(col="black")
```
